/**
 * Assassination Attempt Event Pipeline (CHOICE-BASED)
 *
 * Someone attempts to kill one of your leaders.
 * How will you respond to protect the kingdom?
 *
 * Approaches:
 * - Open Governance (V) - Maintain transparency while protecting the leader
 * - Investigate Thoroughly (P) - Increase security and hunt conspirators
 * - Purge Conspirators (R) - Launch a ruthless crackdown
 */

import type { CheckPipeline } from '../../types/CheckPipeline';
import type { GameCommandContext } from '../../services/gameCommands/GameCommandHandler';
import { AddImprisonedHandler } from '../../services/gameCommands/handlers/AddImprisonedHandler';
import { valueBadge, textBadge, diceBadge } from '../../types/OutcomeBadge';

export const assassinationAttemptPipeline: CheckPipeline = {
  id: 'assassination-attempt',
  name: 'Assassination Attempt',
  description: 'Someone attempts to kill one of your leaders.',
  checkType: 'event',
  tier: 1,

  // Strategic choice - triggers voting system
  // Options ordered: Virtuous (left) → Practical (center) → Ruthless (right)
  strategicChoice: {
    label: 'How will you respond to the assassination attempt?',
    required: true,
    options: [
      {
        id: 'open-governance',
        label: 'Open Governance',
        description: 'Protect the leader but maintain transparent rule',
        icon: 'fas fa-landmark',
        skills: ['diplomacy', 'society'],
        personality: { virtuous: 3 },
        outcomeDescriptions: {
          criticalSuccess: 'Your transparency during the crisis strengthens trust, and the assassin is caught through public cooperation.',
          success: 'Your open approach reassures citizens while the threat is neutralized.',
          failure: 'Your transparency is exploited, and the leader is injured before security arrives.',
          criticalFailure: 'Your refusal to increase security results in a serious injury that incapacitates one of your leaders.'
        },
        outcomeBadges: {
          criticalSuccess: [
            valueBadge('Gain {{value}} Fame', 'fas fa-star', 1, 'positive'),
            diceBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', '1d3', 'positive')
          ],
          success: [
            valueBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', 1, 'positive')
          ],
          failure: [
            valueBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', 1, 'negative'),
            diceBadge('Lose {{value}} Gold (medical)', 'fas fa-coins', '1d3', 'negative')
          ],
          criticalFailure: [
            diceBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', '1d3', 'negative'),
            diceBadge('Lose {{value}} Gold', 'fas fa-coins', '2d3', 'negative'),
            textBadge('1 leader loses their action', 'fas fa-user-injured', 'negative')
          ]
        }
      },
      {
        id: 'practical',
        label: 'Investigate Thoroughly',
        description: 'Increase security and hunt down conspirators',
        icon: 'fas fa-magnifying-glass',
        skills: ['stealth', 'survival'],
        personality: { practical: 3 },
        outcomeDescriptions: {
          criticalSuccess: 'Your investigation uncovers the entire conspiracy, and all conspirators are imprisoned.',
          success: 'Increased security thwarts the attempt and restores confidence.',
          failure: 'Your investigation proves costly but yields few results.',
          criticalFailure: 'The investigation drains resources while the conspiracy remains active.'
        },
        outcomeBadges: {
          criticalSuccess: [
            valueBadge('Gain {{value}} Fame', 'fas fa-star', 1, 'positive'),
            diceBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', '1d3', 'positive')
            // Note: Imprisonment badge is generated by ConvertUnrestToImprisonedHandler
          ],
          success: [
            valueBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', 1, 'positive')
          ],
          failure: [
            valueBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', 1, 'negative'),
            diceBadge('Lose {{value}} Gold', 'fas fa-coins', '1d3', 'negative')
          ],
          criticalFailure: [
            diceBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', '1d3', 'negative'),
            diceBadge('Lose {{value}} Gold', 'fas fa-coins', '2d3', 'negative')
          ]
        }
      },
      {
        id: 'ruthless',
        label: 'Purge Conspirators',
        description: 'Launch a ruthless crackdown on all suspects',
        icon: 'fas fa-skull',
        skills: ['intimidation', 'warfare'],
        personality: { ruthless: 3 },
        outcomeDescriptions: {
          criticalSuccess: 'Your brutal purge eliminates all threats through mass arrests and intimidation.',
          success: 'Your harsh crackdown imprisons suspects and crushes the conspiracy.',
          failure: 'Your excessive force imprisons innocents, breeding resentment.',
          criticalFailure: 'Your brutal overreach creates martyrs, damages your reputation, and imprisons many innocents.'
        },
        outcomeBadges: {
          criticalSuccess: [
            diceBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', '1d3', 'positive')
            // Note: Imprisonment badge is generated by ConvertUnrestToImprisonedHandler
          ],
          success: [
            valueBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', 1, 'positive')
            // Note: Imprisonment badge is generated by ConvertUnrestToImprisonedHandler
          ],
          failure: [
            valueBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', 1, 'negative')
            // Note: Imprisonment badge is generated by AddImprisonedHandler
          ],
          criticalFailure: [
            diceBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', '1d3', 'negative'),
            valueBadge('Lose {{value}} Fame', 'fas fa-star', 1, 'negative')
            // Note: Imprisonment badge is generated by AddImprisonedHandler
          ]
        }
      }
    ]
  },

  skills: [
    { skill: 'stealth', description: 'track the assassin' },
    { skill: 'intimidation', description: 'deter through fear' },
    { skill: 'medicine', description: 'survive wounds' },
    { skill: 'diplomacy', description: 'maintain public trust' },
    { skill: 'society', description: 'investigate conspirators' },
    { skill: 'survival', description: 'escape danger' },
    { skill: 'warfare', description: 'military crackdown' },
  ],

  outcomes: {
    criticalSuccess: {
      description: 'Your security response proves ideal.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
    success: {
      description: 'The threat is neutralized appropriately.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
    failure: {
      description: 'Security concerns remain.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
    criticalFailure: {
      description: 'Your response creates new dangers.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
  },

  preview: {
    calculate: async (ctx) => {
      // Read approach from kingdom store (set by PreRollChoiceSelector voting)
      const { get } = await import('svelte/store');
      const { kingdomData } = await import('../../stores/KingdomStore');
      const kingdom = get(kingdomData);
      const approach = kingdom.turnState?.eventsPhase?.selectedApproach;
      const outcome = ctx.outcome;

      // Find the selected approach option
      const selectedOption = assassinationAttemptPipeline.strategicChoice?.options.find(opt => opt.id === approach);

      // Get outcome badges from the selected approach
      const outcomeType = outcome as 'criticalSuccess' | 'success' | 'failure' | 'criticalFailure';
      const outcomeBadges = selectedOption?.outcomeBadges?.[outcomeType] ? [...selectedOption.outcomeBadges[outcomeType]] : [];

      // Calculate modifiers and prepare game commands based on approach
      let modifiers: any[] = [];
      const commandContext: GameCommandContext = {
        actionId: 'assassination-attempt',
        outcome: ctx.outcome,
        kingdom: ctx.kingdom,
        metadata: ctx.metadata || {}
      };

      if (approach === 'open-governance') {
        // Open Governance (Virtuous)
        if (outcome === 'criticalSuccess') {
          modifiers = [
            { type: 'static', resource: 'fame', value: 1, duration: 'immediate' },
            { type: 'dice', resource: 'unrest', formula: '1d3', negative: true, duration: 'immediate' }
          ];
        } else if (outcome === 'success') {
          modifiers = [
            { type: 'static', resource: 'unrest', value: -1, duration: 'immediate' }
          ];
        } else if (outcome === 'failure') {
          modifiers = [
            { type: 'static', resource: 'unrest', value: 1, duration: 'immediate' },
            { type: 'dice', resource: 'gold', formula: '1d3', negative: true, duration: 'immediate' }
          ];
        } else if (outcome === 'criticalFailure') {
          modifiers = [
            { type: 'dice', resource: 'unrest', formula: '1d3', duration: 'immediate' },
            { type: 'dice', resource: 'gold', formula: '2d3', negative: true, duration: 'immediate' }
          ];
          // Leader loses action
          const { SpendPlayerActionHandler } = await import('../../services/gameCommands/handlers/SpendPlayerActionHandler');
          const actionHandler = new SpendPlayerActionHandler();
          const actionCommand = await actionHandler.prepare(
            { type: 'spendPlayerAction', characterSelection: 'random' },
            commandContext
          );
          if (actionCommand) {
            ctx.metadata._preparedSpendAction = actionCommand;
            if (actionCommand.outcomeBadges) {
              outcomeBadges.push(...actionCommand.outcomeBadges);
            } else if (actionCommand.outcomeBadge) {
              outcomeBadges.push(actionCommand.outcomeBadge);
            }
          }
        }
      } else if (approach === 'practical') {
        // Investigate Thoroughly (Practical)
        if (outcome === 'criticalSuccess') {
          modifiers = [
            { type: 'static', resource: 'fame', value: 1, duration: 'immediate' },
            { type: 'dice', resource: 'unrest', formula: '1d3', negative: true, duration: 'immediate' }
          ];
          // Imprison conspirators - handler will be called during execution
          ctx.metadata._imprisonAmount = 3;
          ctx.metadata._imprisonFormula = '1d3';
        } else if (outcome === 'success') {
          modifiers = [
            { type: 'static', resource: 'unrest', value: -1, duration: 'immediate' }
          ];
        } else if (outcome === 'failure') {
          modifiers = [
            { type: 'static', resource: 'unrest', value: 1, duration: 'immediate' },
            { type: 'dice', resource: 'gold', formula: '1d3', negative: true, duration: 'immediate' }
          ];
        } else if (outcome === 'criticalFailure') {
          modifiers = [
            { type: 'dice', resource: 'unrest', formula: '1d3', duration: 'immediate' },
            { type: 'dice', resource: 'gold', formula: '2d3', negative: true, duration: 'immediate' }
          ];
        }
      } else if (approach === 'ruthless') {
        // Purge Conspirators (Ruthless)
        if (outcome === 'criticalSuccess') {
          modifiers = [
            { type: 'dice', resource: 'unrest', formula: '1d3', negative: true, duration: 'immediate' }
          ];
          // Imprison conspirators (convert unrest to imprisoned)
          const { ConvertUnrestToImprisonedHandler } = await import('../../services/gameCommands/handlers/ConvertUnrestToImprisonedHandler');
          const imprisonHandler = new ConvertUnrestToImprisonedHandler();
          const imprisonCommand = await imprisonHandler.prepare(
            { type: 'convertUnrestToImprisoned', amount: 3, diceFormula: '1d3' },
            commandContext
          );
          if (imprisonCommand) {
            ctx.metadata._preparedImprison = imprisonCommand;
            if (imprisonCommand.outcomeBadges) {
              outcomeBadges.push(...imprisonCommand.outcomeBadges);
            } else if (imprisonCommand.outcomeBadge) {
              outcomeBadges.push(imprisonCommand.outcomeBadge);
            }
          }
        } else if (outcome === 'success') {
          modifiers = [
            { type: 'static', resource: 'unrest', value: -1, duration: 'immediate' }
          ];
          // Imprison conspirators (1d2)
          const { ConvertUnrestToImprisonedHandler } = await import('../../services/gameCommands/handlers/ConvertUnrestToImprisonedHandler');
          const imprisonHandler = new ConvertUnrestToImprisonedHandler();
          const imprisonCommand = await imprisonHandler.prepare(
            { type: 'convertUnrestToImprisoned', amount: 2, diceFormula: '1d2' },
            commandContext
          );
          if (imprisonCommand) {
            ctx.metadata._preparedImprison = imprisonCommand;
            if (imprisonCommand.outcomeBadges) {
              outcomeBadges.push(...imprisonCommand.outcomeBadges);
            } else if (imprisonCommand.outcomeBadge) {
              outcomeBadges.push(imprisonCommand.outcomeBadge);
            }
          }
        } else if (outcome === 'failure') {
          modifiers = [
            { type: 'static', resource: 'unrest', value: 1, duration: 'immediate' }
          ];
          // Imprison innocents (increase imprisoned WITHOUT reducing unrest)
          const addImprisonedHandler = new AddImprisonedHandler();
          const imprisonCommand = await addImprisonedHandler.prepare(
            { type: 'addImprisoned', amount: 2, diceFormula: '1d2' },
            commandContext
          );
          if (imprisonCommand) {
            ctx.metadata._preparedAddImprisoned = imprisonCommand;
            if (imprisonCommand.outcomeBadges) {
              outcomeBadges.push(...imprisonCommand.outcomeBadges);
            } else if (imprisonCommand.outcomeBadge) {
              outcomeBadges.push(imprisonCommand.outcomeBadge);
            }
          }
        } else if (outcome === 'criticalFailure') {
          modifiers = [
            { type: 'dice', resource: 'unrest', formula: '1d3', duration: 'immediate' },
            { type: 'static', resource: 'fame', value: -1, duration: 'immediate' }
          ];
          // Imprison innocents (increase imprisoned WITHOUT reducing unrest)
          const addImprisonedHandler = new AddImprisonedHandler();
          const imprisonCommand = await addImprisonedHandler.prepare(
            { type: 'addImprisoned', amount: 3, diceFormula: '1d3' },
            commandContext
          );
          if (imprisonCommand) {
            ctx.metadata._preparedAddImprisoned = imprisonCommand;
            if (imprisonCommand.outcomeBadges) {
              outcomeBadges.push(...imprisonCommand.outcomeBadges);
            } else if (imprisonCommand.outcomeBadge) {
              outcomeBadges.push(imprisonCommand.outcomeBadge);
            }
          }
        }
      }

      // Store modifiers in context for execute step
      ctx.metadata._outcomeModifiers = modifiers;

      return { resources: [], outcomeBadges };
    }
  },

  execute: async (ctx) => {
    // NOTE: Standard modifiers (unrest, gold, fame) are applied automatically by
    // ResolutionDataBuilder + GameCommandsService via outcomeBadges.
    // This execute() only handles special game commands.

    const { get } = await import('svelte/store');
    const { kingdomData } = await import('../../stores/KingdomStore');
    const kingdom = get(kingdomData);
    const approach = kingdom.turnState?.eventsPhase?.selectedApproach;
    const outcome = ctx.outcome;

    // Execute game commands based on approach and outcome
    if (approach === 'open-governance' && outcome === 'criticalFailure') {
      const actionCommand = ctx.metadata?._preparedSpendAction;
      if (actionCommand?.commit) {
        await actionCommand.commit();
      }
    }

    if ((approach === 'practical' || approach === 'ruthless') &&
        (outcome === 'criticalSuccess' || outcome === 'success')) {
      const imprisonCommand = ctx.metadata?._preparedImprison;
      if (imprisonCommand?.commit) {
        await imprisonCommand.commit();
      }
    }

    // Handle imprisoning innocents for purge failure/critical failure
    if (approach === 'ruthless' && (outcome === 'failure' || outcome === 'criticalFailure')) {
      const addImprisonedCommand = ctx.metadata?._preparedAddImprisoned;
      if (addImprisonedCommand?.commit) {
        await addImprisonedCommand.commit();
      }
    }

    return { success: true };
  },

  traits: ["dangerous"],
};
