/**
 * Notorious Heist Event Pipeline (CHOICE-BASED)
 *
 * A daring theft threatens your kingdom's security and reputation.
 *
 * Approaches:
 * - Track Down and Recover (Virtuous) - Recover stolen goods
 * - Increase Treasury Security (Practical) - Prevent future thefts
 * - Terrorize Underworld (Ruthless) - Brutal crackdown on criminals
 *
 * Based on EVENT_MIGRATION_STATUS.md specifications
 */

import type { CheckPipeline } from '../../types/CheckPipeline';
import type { GameCommandContext } from '../../services/gameCommands/GameCommandHandler';
import { ConvertUnrestToImprisonedHandler } from '../../services/gameCommands/handlers/ConvertUnrestToImprisonedHandler';
import { AddImprisonedHandler } from '../../services/gameCommands/handlers/AddImprisonedHandler';
import { DamageStructureHandler } from '../../services/gameCommands/handlers/DamageStructureHandler';
import { valueBadge, diceBadge } from '../../types/OutcomeBadge';

export const notoriousHeistPipeline: CheckPipeline = {
  id: 'notorious-heist',
  name: 'Notorious Heist',
  description: 'A daring theft threatens your kingdom\'s security and reputation.',
  checkType: 'event',
  tier: 1,

  // Strategic choice - triggers voting system
  // Options ordered: Virtuous (left) → Practical (center) → Ruthless (right)
  strategicChoice: {
    label: 'How will you respond to this major theft?',
    required: true,
    options: [
      {
        id: 'virtuous',
        label: 'Track Down and Recover',
        description: 'Pursue the thieves to recover stolen goods',
        icon: 'fas fa-search',
        skills: ['thievery', 'stealth'],
        personality: { virtuous: 3 },
        outcomeDescriptions: {
          criticalSuccess: 'Thieves caught and stolen goods recovered! Fame spreads.',
          success: 'Most stolen goods recovered through diligent pursuit.',
          failure: 'The trail goes cold. Investigation costs drain resources.',
          criticalFailure: 'Failed pursuit sparks public outrage and drains treasury.'
        },
        outcomeBadges: {
          criticalSuccess: [
            valueBadge('Gain {{value}} Fame', 'fas fa-star', 1, 'positive'),
            diceBadge('Gain {{value}} Gold', 'fas fa-coins', '1d3', 'positive')
          ],
          success: [
            diceBadge('Gain {{value}} Gold', 'fas fa-coins', '1d2', 'positive')
          ],
          failure: [
            valueBadge('Lose {{value}} Gold', 'fas fa-coins', 1, 'negative')
          ],
          criticalFailure: [
            diceBadge('Lose {{value}} Gold', 'fas fa-coins', '1d3', 'negative'),
            valueBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', 1, 'negative')
          ]
        }
      },
      {
        id: 'practical',
        label: 'Increase Treasury Security',
        description: 'Prevent future thefts with better security',
        icon: 'fas fa-shield-alt',
        skills: ['society', 'intimidation'],
        personality: { practical: 3 },
        outcomeDescriptions: {
          criticalSuccess: 'Enhanced security restores confidence. Recovered contraband.',
          success: 'New security measures restore public confidence.',
          failure: 'Security improvements prove costly.',
          criticalFailure: 'Expensive security fails spectacularly.'
        },
        outcomeBadges: {
          criticalSuccess: [
            diceBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', '1d2', 'positive'),
            diceBadge('Gain {{value}} Gold', 'fas fa-coins', '1d2', 'positive')
          ],
          success: [
            valueBadge('Reduce Unrest by {{value}}', 'fas fa-shield-alt', 1, 'positive')
          ],
          failure: [
            valueBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', 1, 'negative')
          ],
          criticalFailure: [
            diceBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', '1d2', 'negative'),
            diceBadge('Lose {{value}} Gold', 'fas fa-coins', '1d2', 'negative')
          ]
        }
      },
      {
        id: 'ruthless',
        label: 'Terrorize Underworld',
        description: 'Brutal response to intimidate criminals',
        icon: 'fas fa-fire',
        skills: ['intimidation', 'performance'],
        personality: { ruthless: 3 },
        outcomeDescriptions: {
          criticalSuccess: 'The underworld is crushed. Mass arrests fill the prisons.',
          success: 'Criminals rounded up through aggressive tactics.',
          failure: 'Innocents caught up in your heavy-handed tactics.',
          criticalFailure: 'Excessive violence causes riots and property damage.'
        },
        outcomeBadges: {
          criticalSuccess: [
            // Note: Aggressive arrest badge (converts 1d4 unrest to imprisoned) generated by handler
          ],
          success: [
            // Note: Arrest badge (converts 1d3 unrest to imprisoned) generated by handler
          ],
          failure: [
            valueBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', 1, 'negative')
            // Note: Innocent imprisonment badge (adds 1d2 imprisoned) generated by handler
          ],
          criticalFailure: [
            diceBadge('Gain {{value}} Unrest', 'fas fa-exclamation-triangle', '1d3', 'negative'),
            valueBadge('Lose {{value}} Fame', 'fas fa-star', 1, 'negative')
            // Note: Structure damage badge generated by handler
          ]
        }
      }
    ]
  },

  skills: [
    { skill: 'thievery', description: 'understand criminal methods' },
    { skill: 'stealth', description: 'track the thieves' },
    { skill: 'society', description: 'investigate connections' },
    { skill: 'intimidation', description: 'show of force' },
    { skill: 'performance', description: 'public demonstration' },
  ],

  outcomes: {
    criticalSuccess: {
      description: 'Your response proves highly effective.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
    success: {
      description: 'Your approach succeeds.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
    failure: {
      description: 'Your response encounters complications.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
    criticalFailure: {
      description: 'Your handling backfires badly.',
      endsEvent: true,
      modifiers: [],
      outcomeBadges: []
    },
  },

  preview: {
    calculate: async (ctx) => {
      // Read approach from kingdom store (set by PreRollChoiceSelector voting)
      const { get } = await import('svelte/store');
      const { kingdomData } = await import('../../stores/KingdomStore');
      const kingdom = get(kingdomData);
      const approach = kingdom.turnState?.eventsPhase?.selectedApproach;
      const outcome = ctx.outcome;

      // Find the selected approach option
      const selectedOption = notoriousHeistPipeline.strategicChoice?.options.find(opt => opt.id === approach);

      // Get outcome badges from the selected approach
      const outcomeType = outcome as 'criticalSuccess' | 'success' | 'failure' | 'criticalFailure';
      const outcomeBadges = selectedOption?.outcomeBadges?.[outcomeType] ? [...selectedOption.outcomeBadges[outcomeType]] : [];

      const commandContext: GameCommandContext = {
        actionId: 'notorious-heist',
        outcome: ctx.outcome,
        kingdom: ctx.kingdom,
        metadata: ctx.metadata || {}
      };

      if (approach === 'virtuous') {
        // Track Down and Recover (Virtuous)
        // All outcomes handled by standard badges (gold, fame)
      } else if (approach === 'practical') {
        // Increase Treasury Security (Practical)
        // All outcomes handled by standard badges (unrest, gold)
      } else if (approach === 'ruthless') {
        // Terrorize Underworld (Ruthless)
        if (outcome === 'criticalSuccess') {
          // Aggressive mass arrests - convert 1d4 unrest to imprisoned
          const imprisonHandler = new ConvertUnrestToImprisonedHandler();
          const imprisonCommand = await imprisonHandler.prepare(
            { type: 'convertUnrestToImprisoned', amount: 4, diceFormula: '1d4' },
            commandContext
          );
          if (imprisonCommand) {
            ctx.metadata._preparedImprison = imprisonCommand;
            if (imprisonCommand.outcomeBadges) {
              outcomeBadges.push(...imprisonCommand.outcomeBadges);
            } else if (imprisonCommand.outcomeBadge) {
              outcomeBadges.push(imprisonCommand.outcomeBadge);
            }
          }
        } else if (outcome === 'success') {
          // Convert 1d3 unrest to imprisoned
          const imprisonHandler = new ConvertUnrestToImprisonedHandler();
          const imprisonCommand = await imprisonHandler.prepare(
            { type: 'convertUnrestToImprisoned', amount: 3, diceFormula: '1d3' },
            commandContext
          );
          if (imprisonCommand) {
            ctx.metadata._preparedImprison = imprisonCommand;
            if (imprisonCommand.outcomeBadges) {
              outcomeBadges.push(...imprisonCommand.outcomeBadges);
            } else if (imprisonCommand.outcomeBadge) {
              outcomeBadges.push(imprisonCommand.outcomeBadge);
            }
          }
        } else if (outcome === 'failure') {
          // +1 Unrest, imprison 1d2 innocents
          const addImprisonedHandler = new AddImprisonedHandler();
          const imprisonCommand = await addImprisonedHandler.prepare(
            { type: 'addImprisoned', amount: 2, diceFormula: '1d2' },
            commandContext
          );
          if (imprisonCommand) {
            ctx.metadata._preparedAddImprisoned = imprisonCommand;
            if (imprisonCommand.outcomeBadges) {
              outcomeBadges.push(...imprisonCommand.outcomeBadges);
            } else if (imprisonCommand.outcomeBadge) {
              outcomeBadges.push(imprisonCommand.outcomeBadge);
            }
          }
        } else if (outcome === 'criticalFailure') {
          // +1d3 Unrest, -1 Fame, damage 1 structure (riot)
          const damageHandler = new DamageStructureHandler();
          const damageCommand = await damageHandler.prepare(
            { type: 'damageStructure', count: 1 },
            commandContext
          );
          if (damageCommand) {
            ctx.metadata._preparedDamage = damageCommand;
            if (damageCommand.outcomeBadges) {
              outcomeBadges.push(...damageCommand.outcomeBadges);
            } else if (damageCommand.outcomeBadge) {
              outcomeBadges.push(damageCommand.outcomeBadge);
            }
          }
        }
      }

      return { resources: [], outcomeBadges };
    }
  },

  execute: async (ctx) => {
    // NOTE: Standard modifiers (unrest, gold, fame) are applied automatically by
    // ResolutionDataBuilder + GameCommandsService via outcomeBadges.
    // This execute() only handles special game commands.

    // Execute imprisonment (ruthless CS/S - converts unrest to imprisoned)
    const imprisonCommand = ctx.metadata?._preparedImprison;
    if (imprisonCommand?.commit) {
      await imprisonCommand.commit();
    }

    // Execute innocent imprisonment (ruthless F - adds imprisoned without reducing unrest)
    const addImprisonedCommand = ctx.metadata?._preparedAddImprisoned;
    if (addImprisonedCommand?.commit) {
      await addImprisonedCommand.commit();
    }

    // Execute structure damage (ruthless CF)
    const damageCommand = ctx.metadata?._preparedDamage;
    if (damageCommand?.commit) {
      await damageCommand.commit();
    }

    return { success: true };
  },

  traits: ["dangerous"],
};
