// Auto-generated TypeScript types for Kingdom Incidents
// Generated by scripts/generate-types.py
// DO NOT EDIT MANUALLY - Run 'npm run generate-types' to update

/**
 * NOTE: Incidents use the same core structure as Events.
 * We re-export event types and add incident-specific interface.
 * 
 * Incidents use severity ('minor', 'moderate', 'major') for explicit categorization.
 */

// Re-export all event types for use with incidents
export type {
  EventSkill,
  KingdomSkill,
  EventTrait,
  EventLocation,
  EventTier,
  ResourceType,
  ModifierDuration,
  EventModifier,
  EventOutcome,
  EventEffects,
  KingdomEvent
} from './events';

/**
 * Kingdom Incident (same structure as event)
 * 
 * Incidents are similar to events but:
 * - Always triggered by high Unrest (not random)
 * - Have severity levels (minor, moderate, major)
 * - Use same skill/effect structure as events
 */
export interface KingdomIncident {
  id: string;
  name: string;  // Display name for UI
  severity: 'minor' | 'moderate' | 'major';
  description: string;
  skills?: EventSkill[];
  effects: EventEffects;
  traits?: EventTrait[];  // Event traits (beneficial, dangerous, ongoing)
}

/**
 * Type guard to check if an object is a KingdomIncident
 */
export function isKingdomIncident(obj: any): obj is KingdomIncident {
  return (
    typeof obj === 'object' &&
    typeof obj.id === 'string' &&
    typeof obj.name === 'string' &&
    typeof obj.description === 'string' &&
    typeof obj.severity === 'string' &&
    typeof obj.effects === 'object'
  );
}

/**
 * Helper to generate display name from incident ID
 */
export function getIncidentDisplayName(incident: KingdomIncident): string {
  return incident.id
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
